### ISSUE TITLE
How to turn off the multilingual panel hotkey

### ISSUE THREAD

**Issue by m13253** [Elypha/BilingualTooltips#3]
First, thanks for your development of this plugin.
But, since v1.1.0.0, the newly added “Multilingual panel” feature has been causing problems to me.

Its hotkey is bound to `X` by default, which is highly likely already bound to a combat action.
Thus, this panel may accidentally pop up during a duty when the player presses `X`, trying to cast a magic.
Since it’s during a duty, the player may not be able to figure out why an unknown pop-up window suddenly covers the screen and takes over input focus, potentially causing a party wipe.

I myself spent a few minutes in the duty, locating the cause and disabling this plugin, because I realized I didn’t find a way to disable this hotkey other than changing it into some super complex combo.
Did I miss anything? Please let me know which settings I should configure to disable this newly added feature.

(P.S. I recommend not introducing new hotkeys during plugin update. In my own opinion, it’s safer to let the user miss a new feature, rather than accidentally occupying a hotkey for combat action.)

**Comment by Elypha** [comment]
hi thanks for reaching out!

that default hotkey was a mistake and I didn't notice until release. often a new hotkey defaults to one key stroke with at least one key modifier. just saying that it was not intentional or by design.

the default configuration inherits settings in my development environment thus most features get released more or less in a pre configured manner. I'll improve the workflow and try to ship updates with switchs default to off in the future.

I hope the new update can make the plugin more friendly and easier to use and hope you still enjoy it

**Comment by m13253** [comment]
Closing as of v1.2.0.0 update.
